# fly.toml app configuration file generated for kraai on 2024-01-04T13:57:42+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kraai"
primary_region = "syd"

[env]
  NEXTAUTH_URL="https://www.kraai.app"
  DISCORD_CLIENT_ID="1191987164758671400"
  GOOGLE_CLIENT_ID="825973011159-e3ok7kg9v1v1r4ito19ad85ifg1i5r4l.apps.googleusercontent.com"

[build]

[deploy]
  release_command = "pnpm run db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
